### ISSUE TITLE
Clarify which is the "official" repository now

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/wedderga#5]
On http://gap-packages.github.io there are now two links to wedderga: once to this repo, and once to BitBucket.

Perhaps the link to BitBucket should be removed?

**Comment by olexandr-konovalov** [comment]
Done in https://github.com/gap-packages/gap-packages.github.io/commit/d44eeb90d96b1a0e2994736d6cfedf1d403b9cf3 (for UnitLib as well).
