### ISSUE TITLE
Update homepage URL in README (and perhaps elsewhere)

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/wedderga#8]

**Comment by olexandr-konovalov** [comment]
Sure. There is no yet release made from this repo and hosted at GitHub pages. Same for several other packages of mine. A Shoemaker without shoes :)

**Comment by olexandr-konovalov** [comment]
@fingolfin P.S. but anyhow I certainly acknowledge helping me to create a TODO list - even if for me that was obvious task I kept in my head, it helps to me to memorise it quicker when I will return to the package, and helps others who may be interested to see what's the status of the package.

**Comment by olexandr-konovalov** [comment]
@fingolfin P.P.S. Same reason why the URL of the website is not in the repository description.

**Comment by olexandr-konovalov** [comment]
Published now at https://gap-packages.github.io/wedderga/
