### ISSUE TITLE
wedderga testsuite fails on master when using a minimal set of packages

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/wedderga#84]
It looks as if perhaps testinstall.g needs `LoadPackage("atlasrep")`?
```
########> Diff in /home/gap/inst/gap-master/pkg/wedderga-4.10.0/tst/wedderga07.tst:72
# Input is:
G:=AtlasGroup("J2");
# Expected output:
<permutation group of size 604800 with 2 generators>
# But found:
Error, Variable: 'AtlasGroup' must have a value
########
```
Full log is available at https://travis-ci.org/github/gap-infra/gap-docker-pkg-tests-master/jobs/710776137

**Comment by drallenherman** [comment]
Yes, we kept this atlas group test in the 4.10.0 documentation for demonstration purposes only.  So it is not crucial and if it causes a problem it could be taken out.

**Comment by fingolfin** [comment]
You could just turn it from an `<Example>` into a `<Log>` then it won't be included in the tests. Or else just add `LoadPackage("atlasrep");` to the start of your `tst/testall.g`.

**Comment by olexandr-konovalov** [comment]
I'm for adding `LoadPackage("atlasrep");` call.

**Comment by drallenherman** [comment]
Okay.  Go ahead @alex-konovalov let's load the package then.   Can you take care of it?

**Comment by olexandr-konovalov** [comment]
@drallenherman yes, I wil!

**Comment by olexandr-konovalov** [comment]
Still here e.g. https://travis-ci.org/github/gap-infra/gap-docker-pkg-tests-master/jobs/714790646 - should do in August.
