### ISSUE TITLE
Please make a new release (v4.10.1 ?)

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/wedderga#88]
... so that @wilfwilson's pluralization fixes from 1.5 years ago final reach the distribution, and we can then merge this related GAP changes :-).

Or if you prefer, I am happy to make that release for you, it should only take 5 minutes, there was really only one code change since the last release, after all

**Comment by olexandr-konovalov** [comment]
Released in 5dfdf6cfda9d955841192b54bb088c12100c3e79
